### ISSUE TITLE
Test runner doesn't validate non existent class or test case of tsqlt

### ISSUE THREAD

**Issue by ronniekapoor** [GoEddie/tSQLt-Clients#2]
Test runner methods return true as passed even if any invalid name of a class or a test is passed to it. It should return fail as no test case was run by tsqlt or no class is present at database end for tsqlt.
![snap 2017-04-12 at 15 19 03](https://cloud.githubusercontent.com/assets/5711315/24951874/702263e6-1f93-11e7-8638-64d574d93358.png)
![snap 2017-04-12 at 15 19 27](https://cloud.githubusercontent.com/assets/5711315/24951873/7021cc42-1f93-11e7-8a78-1e38cdf75e9e.png)

**Comment by ronniekapoor** [comment]
similar is the case with run class method

**Comment by GoEddie** [comment]
This has been fixed with the latest release:

https://github.com/GoEddie/tSQLt-Clients/releases/tag/1.0.0.4

Thanks for reporting it :)

**Comment by ronniekapoor** [comment]
Hi Eddie,

Thanks for fixing the issue. Can you also please publish the package over nuget?

thanks and regards
ronnie

**Comment by GoEddie** [comment]
Done :)

https://www.nuget.org/packages/tSQLt.Client.Net/1.0.0.4
